### ISSUE TITLE
Make WikiPathways plugin part of core application

### ISSUE THREAD

**Issue by mkutmon** [PathVisio/pathvisio#18]
PathVisio will be main editor for WikiPathways, so WikiPathways plugin should become part of the core application.

**Comment by markwoon** [comment]
Do you mean the WikiPathways plugin gets distributed with the PathVisio application by default, or do you mean actually integrating it into the core application?

If it becomes integral to PathVisio then that could be a problem for us.  We build our plugin on top of the core PathVisio GUI.  If I remember correctly, I've tried eliminating the gex and visualization plugin before, but it was integrated tightly enough that I couldn't just not bundle those plugins.  Instead, I had to write additional code to hide the UI from those plugins.

I would like to see all plugins independent and optional.  They can be bundled together by default, but shouldn't be required.  Otherwise it's not really a plugin anymore but core functionality.

**Comment by mkutmon** [comment]
Sorry should have been more specific! I meant it should be distributed with the core application. I'll keep your comment in mind!

**Comment by mkutmon** [comment]
I decided to use another solution for loading the WP plugin. If the application is started with the "-wpid" argument to open a pathway through the plugin, the application checks if the plugin is already installed and if not, it will be installed through the plugin manager. No prepackaging is needed. 
See commit: e3f56701718b7f2931e078204c62c1acae64d1d4
