### ISSUE TITLE
Wikidata database label for Metabolite nodes

### ISSUE THREAD

**Issue by DeniseSl22** [PathVisio/pathvisio#42]
Could a database label for Wikidata-identifiers be added please :)?

**Comment by JonathanMELIUS** [comment]
This is because in the[ datasources configuration files ](https://github.com/bridgedb/BridgeDb/blob/master/org.bridgedb.bio/resources/org/bridgedb/bio/datasources.txt), Wikidata is registered as a ["secondary identifiers"](https://github.com/bridgedb/BridgeDb/blob/master/org.bridgedb.bio/resources/org/bridgedb/bio/datasources_headers.txt). 
( columns 8: 0 = secondary identifiers); e.g :

- Wikidata	Wd	http://www.wikidata.org	http://www.wikidata.org/wiki/$id	Q407962	metabolite		0	urn:miriam:wikidata	^Q\d+$	Wikidata

So it means that if we want Wikidata to appear in the metabolite dialog box in PathVisio, we have to change the 0 to 1. 

@egonw, @mkutmon : Any reasons why Wikidata is a "secondary identifiers" ?

**Comment by egonw** [comment]
I think that may originate from the days when I was not sure about the quality yet... but I'm OK to make it a primary ID now... @mkutmon, also OK?

I think we then need to update BridgeDb in PathVisio, right? Because we still cannot update just the datasources.txt (or .ttl) in PathVisio without a new BridgeDb release (something that annoys me)...

**Comment by egonw** [comment]
Related to https://github.com/PathVisio/pathvisio/issues/43

**Comment by DeniseSl22** [comment]
I think we should look through the whole datasources configuration files -list, since you (Egon) asked me yesterday to manually change Pubchem_substance to pubchem_ compounds. However, when people still have the option to use Pubchem_sbstance as a database, they can keep adding those as a metabolite identifier.

So I think we should evaluate the list, change the 0 to 1 for databases we do want to appear in Pathvisio, change the 1 to 0 for databases we do not want to appear in Pathvisio, and then update BridgeDB.

**Comment by egonw** [comment]
Denise, maar niet alleen de data source veranderen, maar ook de identifier!

Yes, making PubChem substance a secondairy data source sounds like a good idea!

**Comment by DeniseSl22** [comment]
Yes I got that I need to change the identifier as well, otherwise it is just wrong.

So, are there any other databases that can be changed from primary to secondary and vise versa?

**Comment by DeniseSl22** [comment]
Apparently InCHI -IDs are not valid anymore in PathVisio (results in broken links, [check here]( https://wikipathways.slack.com/archives/C0KEWBKK7/p1502214703214306). So, this identifier option should also be removed I think.

**Comment by egonw** [comment]
The problem with InChIs is that BridgeDb does not support them for many compounds, as the String length exceeds what is allowed BridgeDb's Derby backend...

**Comment by DeniseSl22** [comment]
Okay that explains. But the InCHIKey is good to use as identifier?
About the secondary data IDs: according to Tina and Jonathan, this should be changed in the metabolites Bridge DB file (so that people cannot use certain databases which are known to give problems, like Pubchem substance, in PathVisio).

**Comment by mkutmon** [comment]
@egonw did you change Wikidata to primary? because even after your pull request with v2.2.0 it doesn't show up. When I check it doesn't seem to primary. @JonathanMELIUS can you confirm this?

**Comment by mkutmon** [comment]
hmm seems to be primary in datasources.txt at the moment - need to check to make sure I have got the correct bridgedb jars

**Comment by mkutmon** [comment]
okay this is weird - in tag 2.2.0 of BridgeDb Wikidata seems to be a primary ds (https://github.com/bridgedb/BridgeDb/blob/release_2.2.0/org.bridgedb.bio/resources/org/bridgedb/bio/datasources.txt) but if I unjar the org.bridgedb.bio.jar and look at the datasources.txt file in there it is a secondary ds. @egonw @JonathanMELIUS any ideas what might be going on? 

In any case, as long as it isn't a primary ds in the datasources.txt it doesn't show up in the dropdown box in PV.

**Comment by egonw** [comment]
My bad! My PR was was from longer ago, but I was focussed on the bug fix... the commit to make Wikidata primary was after that PR: https://github.com/bridgedb/BridgeDb/commit/7b91a01c91497d2b5c7a5204880435215d550426

I will make a new PR!

**Comment by DeniseSl22** [comment]
Nice! looking forward to see that one ;)
