### ISSUE TITLE
Visualization save option

### ISSUE THREAD

**Issue by youssefwalid** [PathVisio/pathvisio#92]
Currently, it is necessary to set up new visualization options every time one opens Pathvisio (For example to visualize logFC, p-value etc). Requested is an option to be able to save a created visualization setup.

**Comment by mkutmon** [comment]
actually, the visualization is saved with every dataset that is loaded. Instead of clicking "Import expression data", you can "Select expression data" and load a previously created .pgex file. That file also has an associated visualization file (stored in a xml file). The visualization is then automatically loaded.
